server:
  port: 8769
spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    #设置路由映射一：api-a
    api-a:
      path: /orderService/**
      serviceId: ORDER-SERVICE
    #设置路由映射二：api-b
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

logging:
  level:
    org.springframework: debug